### ISSUE TITLE
Uploaded product images synchronization

### ISSUE THREAD

**Issue by ASergey** [absalomedia/prestashop-12-factor#2]
Hi.

How do you use bucketeer? Does it allow to upload product images from shop admin panel to s3 bucket without any manual files synchronization or other black magic?

**Comment by absalomedia** [comment]
Bucketeer allows you to manage the S3 instance from Heroku:
https://devcenter.heroku.com/articles/bucketeer

**Comment by ASergey** [comment]
How do upload images and other stuff to S3?

**Comment by absalomedia** [comment]
Here's the Buckeeter reference on S3 image uploads:
https://devcenter.heroku.com/articles/bucketeer#using-with-the-aws-cli-uploading-files

**Comment by ASergey** [comment]
Thanks, I've already read it.
In other words you synchronize product images manually.
